//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> gravadas { get; set; }
        public Nullable<decimal> totales { get; set; }
        public Nullable<int> idventas { get; set; }
        public int idDetalleventa { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
